//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Taksi
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CompanyBaseEntities : DbContext
    {
        public CompanyBaseEntities()
            : base("name=CompanyBaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BrandCars> BrandCars { get; set; }
        public virtual DbSet<Car> Car { get; set; }
        public virtual DbSet<Client> Client { get; set; }
        public virtual DbSet<ColorCar> ColorCar { get; set; }
        public virtual DbSet<DrivingLicenseCategory> DrivingLicenseCategory { get; set; }
        public virtual DbSet<Employee> Employee { get; set; }
        public virtual DbSet<GradeClient> GradeClient { get; set; }
        public virtual DbSet<GradeUser> GradeUser { get; set; }
        public virtual DbSet<Order> Order { get; set; }
        public virtual DbSet<OrderStatus> OrderStatus { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<ViewCar> ViewCar { get; set; }
        public virtual DbSet<ViewOrder> ViewOrder { get; set; }
        public virtual DbSet<WeightLimit> WeightLimit { get; set; }
    }
}
